#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Haru Motoyama
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random
from collections import Counter
import subprocess

kuji = ["大吉", "中吉", "小吉", "凶"]

results = [random.choice(kuji) for _ in sys.stdin]

counter = Counter(results)

for key, value in counter.items():
    subprocess.run(["echo", f"{value} {key}"])


